### ISSUE TITLE
artwork.js in artwork/components/src

### ISSUE THREAD

**Issue by itsina96** [fac19/week10-ArtAttack#13]

**Comment by Lizzy-j** [comment]
- [ ] Create an array of object IDs to use and this to the fetch request

**Comment by Lizzy-j** [comment]
Japanese: 438011, 25656, 78141, 78060, 53219
Impressionist: 208222, 436532, 459112, 11234
Renoir: 438815 (not sure where to classify this painting?)
Neoclassicism: 459106
Post-impressionism: 435875, 435885
Other: 435683, 437052
