### ISSUE TITLE
Same artwork bugfix suggestion

### ISSUE THREAD

**Issue by mr-bagglesworth** [fac19/week10-ArtAttack#36]
#29 

You might be able to solve this by doing something like the following in `displayartwork.js`. Please note that I have not tested it though.

```
React.useEffect(() => {
    handleArtwork().then((newArtwork) => {
      if (newArtwork.primaryImage === artwork.primaryImage) {
        // could refresh the page to get another artwork here
        window.location.reload();
      }
      setArtwork(newArtwork)
    });
  }, [])
```

**Comment by Lizzy-j** [comment]
Thank you for the suggestion, this appears to have fixed the issue

**Comment by Lizzy-j** [comment]
Thank you for the suggestion, this appears to have fixed the issue
